### ISSUE TITLE
JTAC | CCA vs 9 Line 

### ISSUE THREAD

**Issue by DeRampage** [TaskForce47/TF47-Guides#4]
CCA -> Helo
Check In 

Print Forms & Video

9-Line -> Fixed Wing
Check In 

Print Forms & Video

**Comment by DeRampage** [comment]
@Lizzyx3 die Flagge bitte weniger seitlich gezogen. 
1. Ersetze "Fire Mission" durch "Request Fire Support" und bei "G/U send it" ersetzen durch "A/C send it"

4. Target Description: (Infantery in the open, Tank in forest)

CCA-Basisinformationen weg

**Comment by Lizzyx3** [comment]
Update ist raus
